# Generated by Django 2.0.4 on 2019-01-23 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PMGMP', '0002_remove_pmgbpmodel_parameters'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Parameters',
            new_name='Parameter',
        ),
    ]
