# Generated by Django 2.0.4 on 2019-01-23 23:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PMGMP', '0003_auto_20190123_2323'),
    ]

    operations = [
        migrations.AddField(
            model_name='pmgbpmodel',
            name='parameters',
            field=models.ManyToManyField(to='PMGMP.Parameter'),
        ),
    ]
