# Generated by Django 2.0.4 on 2018-10-19 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sim_RT_Runner', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation',
            name='start_datetime',
        ),
    ]
