# Generated by Django 2.0.4 on 2018-10-19 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Sim_RT_Runner', '0003_simulation_start_datetime'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simulation',
            name='task_id',
        ),
    ]
