# Generated by Django 2.0.4 on 2018-10-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sim_RT_Runner', '0004_remove_simulation_task_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='simulation',
            name='running',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
